# Generated by Django 6.1 on 2026-09-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JejuWeather',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('nx', models.IntegerField()),
                ('ny', models.IntegerField()),
            ],
            options={
                'db_table': 'weather_jejuweather',
                'managed': False,
            },
        ),
    ]
