# Generated by Django 6.1 on 2026-09-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255, verbose_name='이미지 경로')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='장소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'albums_album',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
